"""Version identities for the QEC NEXUS bridge."""

QEC_PACKAGE_VERSION = "170.2.1"
NEXUS_EXECUTION_CONTRACT_VERSION = "170.2.0"
NEXUS_REPLICATION_RECEIPT_VERSION = "170.2.1"
QEC_NEXUS_BRIDGE_VERSION = NEXUS_REPLICATION_RECEIPT_VERSION
SUPPORTED_NEXUS_BRIDGE_VERSIONS = (NEXUS_EXECUTION_CONTRACT_VERSION,)
